BackendBundle\Entity\User:
    properties:
        name:
            - NotBlank: {message: "El nombre no puede estar vacio"} 
        surname:
            - NotBlank: {message: "Los apellitos no pueden estar vacio"}
        nick:
            - NotBlank: {message: "El nick no puede estar vacio"}
        email:
            - NotBlank: {message: "El nick no puede estar vacio"}
            - Email:
                message: El email {{ value }} no es valido.
                checkMX: true
                